PUT https://dev.termx.org/api/transformation-definitions/20
Content-Type: application/json

{
  "id": 20,
  "name": "AstmMsgQueryAllOrdersToFhirBundle",
  "mapping": {
    "name": "main",
    "type": "mapping",
    "source": "static",
    "reference": {
      "content": "/// url = 'http://hl7.org/fhir/StructureMap/AstmMsgQueryAllOrdersToFhirBundle'\n/// name = 'AstmMsgQueryAllOrdersToFhirBundle'\n/// title = 'AstmMsgQueryAllOrdersToFhirBundle'\n\nuses \"http://hl7.org/fhir/StructureDefinition/Bundle\" alias Bundle as source\nuses \"http://hl7.org/hapi-v2-parser/StructureDefinition/ASTM_MSG\" alias ASTM_MSG as target\n\ngroup example(source src : Bundle, target tgt : ASTM_MSG) {\n  \n}"
      }
  },
  "resources": [
    {
      "name": "ASTM_MSG",
      "type": "definition",
      "source": "local",
      "reference": {
        "localId": "434"
      }
    },
    {
      "name": "Bundle",
      "type": "definition",
      "source": "url",
      "reference": {
        "resourceServerId": 100662,
        "resourceUrl": "/StructureDefinition/Bundle"
      }
    },
    {
      "name": "H",
      "type": "definition",
      "source": "local",
      "reference": {
        "localId": "437"
      }
    },
    {
      "name": "P",
      "type": "definition",
      "source": "local",
      "reference": {
        "localId": "443"
      }
    },
    {
      "name": "R",
      "type": "definition",
      "source": "local",
      "reference": {
        "localId": "446"
      }
    },
    {
      "name": "O",
      "type": "definition",
      "source": "local",
      "reference": {
        "localId": "442"
      }
    },
    {
      "name": "L",
      "type": "definition",
      "source": "local",
      "reference": {
        "localId": "439"
      }
    }
  ]
}
